MONGODB_HOST: mongodb-{{ env }}.learndevopskills.shop
REDIS_HOST: redis-{{ env }}.learndevopskills.shop
MYSQL_HOST: mysql-{{ env }}.learndevopskills.shop 
RABBITMQ_HOST: rabbitmq-{{ env }}.learndevopskills.shop 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.learndevopskills.shop
CART_HOST: cart.backend-alb-{{ env }}.learndevopskills.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.learndevopskills.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.learndevopskills.shop
USER_HOST: user.backend-alb-{{ env }}.learndevopskills.shop
